GET http://localhost:3000/players/

GET http://localhost:3000/players/2

PUT http://localhost:3000/players/2
content-type:application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}